#!/usr/bin/env python2
import os
import time
import datetime
import sys
import json


DB = os.path.expanduser('~/hours.json')
DB_HUMAN = os.path.expanduser('~/hours.txt')
HOURS_PER_MONTH = 160

if os.path.exists(DB):
    db = json.load(open(DB))
else:
    db = []


def get_time(t):
    if not t:
        return int(time.time())
    else:
        try:
            dt = datetime.datetime.strptime(t, "%H:%M")
            dt = datetime.datetime.now().replace(hour=dt.hour, minute=dt.minute)
        except ValueError:
            dt = datetime.datetime.strptime(t, "%d.%m.%Y-%H:%M")
        return int(time.mktime(dt.timetuple()))


def checkin(when_or_message=None, message=None):
    if db:
        last_checkin = db[-1]
        assert 'out' in last_checkin, "Already checked in"
    try:
        get_time(when_or_message)
    except:
        message = when_or_message
        when_or_message = None
    db.append({'in': get_time(when_or_message), 'message': message})


def checkout(when_or_message=None, message=None):
    last_checkin = db[-1]
    assert 'in' in last_checkin, "Not yet checked in"
    assert 'out' not in last_checkin, "Already checked out"
    if message:
        last_checkin['message'] = message
    try:
        get_time(when_or_message)
    except:
        last_checkin['message'] = when_or_message
        when_or_message = None
    last_checkin['out'] = get_time(when_or_message)


def nextmonth(m):
    if m == 12:
        return 1
    return m + 1


def save_db():
    json.dump(db, open(DB, 'w'))

    prevmonth = None
    summonth = datetime.timedelta()
    output = []

    total = []

    def format_duration(delta):
        totalseconds = delta.days * 60 * 60 * 24 + delta.seconds
        h, s = divmod(totalseconds, 3600)
        return '%dh %dm' % (h, int(s/60))

    def summary(delta):
        output.append('')
        output.append(' '*25 + 'Total: %s' % format_duration(delta))
        output.append('')
        output.append('')
        total.append(summonth)

    for entry in db:
        checkin_datetime = datetime.datetime.fromtimestamp(entry['in'])

        if 'out' in entry:
            checkout_datetime = datetime.datetime.fromtimestamp(entry['out'])
            line_format = "{checkin} - {checkout} = {duration}  '{message}'"
        else:
            checkout_datetime = datetime.datetime.now().replace(microsecond=0)
            line_format = "{checkin} -  NOW  = {duration}  '{message}'"

        if prevmonth != checkin_datetime.month:
            if prevmonth is not None:
                summary(summonth)
                summonth = datetime.timedelta()
                expected_next_month = nextmonth(prevmonth)
                while expected_next_month != checkin_datetime.month:
                    summary(datetime.timedelta())
                    expected_next_month = nextmonth(expected_next_month)
            output.append(checkin_datetime.strftime('%B %Y'))
            output.append('=' * 20)
            prevmonth = checkin_datetime.month

        summonth += (checkout_datetime - checkin_datetime)
        message = entry.get('message')

        output.append(line_format.format(
            checkin=checkin_datetime.strftime('%a, %d. %b\t%H:%M'),
            checkout=checkout_datetime.strftime('%H:%M'),
            duration=checkout_datetime - checkin_datetime,
            message=message
        ))


    summary(summonth)

    missing = datetime.timedelta(hours=HOURS_PER_MONTH) * len(total) \
              - sum(total, datetime.timedelta())
    output.extend(['Total missing: %s' % format_duration(missing), ''])

    open(DB_HUMAN, 'w').write('\n'.join(output))


def main():
    if len(sys.argv) > 1:
        {'in': checkin, 'out': checkout}[sys.argv[1]](*sys.argv[2:])
    save_db()
    print open(DB_HUMAN).read()


main()
